### ISSUE TITLE
Show a message instead of an empty list

### ISSUE THREAD

**Issue by Chezus** [thememesquad/sempaibot#13]
We should show a message, or an error message instead of showing an empty list whenever a list is empty.

There are four lists right now (Ignore, Permission, Roles, Modules, osu! Follow), but only two of them (Ignore and osu! Follow) can possibly be empty. So only those two need an implementation and a proper response message.

Implementation:
- [x] IGNORE_LIST_EMPTY message
- [x] OSU_FOLLOW_LIST_EMPTY message

Normal mode versions:
- [x] IGNORE_LIST_EMPTY message
- [x] OSU_FOLLOW_LIST_EMPTY message

Tsundere versions:
- [ ] IGNORE_LIST_EMPTY message
- [ ] OSU_FOLLOW_LIST_EMPTY message

**Comment by calvinbaart** [comment]
No need to keep this open since we have the Tsundere -> Normal fallback for responses.
