### ISSUE TITLE
Notification system

### ISSUE THREAD

**Issue by calvinbaart** [thememesquad/sempaibot#15]
We need a system which users of sempaibot can use to get in contact with the admins.
Something like:
"sempai notify ......"
and for the developers side:
"sempai show notifications"

This system can also be used from the developers side to broadcast a message over all the connected servers:
"sempai notify We now have a new module named '....' etc."

**Comment by RukiaXi** [comment]
Going to change command admin broadcast to: "sempai announce *message*"

**Comment by RukiaXi** [comment]
Also going to change user command to "sempai report *message*"

**Comment by RukiaXi** [comment]
Added reports to sem/development. Code quality check and testing please :).

**Comment by calvinbaart** [comment]
Alright, added a few comments on github. Still need to test it though.

**Comment by Chezus** [comment]
I feel like we should have the possibility for custom messages for when we restart Sempai after adding a new feature. The announce message is good too, but we should really inform people upon going online again instead of showing a confusing default message.

**Comment by calvinbaart** [comment]
Not sure if this is needed anymore. I just added a notification system for recent changes in 25e92785b2d9dbdd4041d017c4545416342f6dc0

And the original idea was so that server admins could directly contact us through sempai but we already have the support discord for that (plus ofc the github issue page).

Thoughts?

**Comment by Chezus** [comment]
Yeah, I agree. But then again we also have the announcements tab for change logs... But I agree about the reports thing anyway. Also if we do our jobs right we won't even need the reports section!

**Comment by Chezus** [comment]
Close if you want.
