### ISSUE TITLE
[osu! module] Limit number of people a server can follow to prevent abuse

### ISSUE THREAD

**Issue by Chezus** [thememesquad/sempaibot#17]
This is an important feature before release. I figure it should be adjustable for us on a per-server basis (upon request) as to prevent abuse.

- [x]  Limit number of people a server can follow to 50.
- [x] Make the limit adjustable for superadmins.
- [x] Make the limit adjustable for superadmins, remotely.

**Comment by calvinbaart** [comment]
Fixed in 912c7d3
