### ISSUE TITLE
Improve Sempai user experience

### ISSUE THREAD

**Issue by Chezus** [thememesquad/sempaibot#18]
We need to improve Sempai's user experience. We're not really consistent with our command usage at all and it's leading to frustrations. We should redo it a bit. We need to discuss this a bit, but here's my personal list of things that should probably get changed. I think the solution here is to support both, in most cases:

These ones are inconsistent. We really need both:

- "Sempai stop following" also needs "Sempai unfollow"
- "Sempai unignore USER" also needs "Sempai stop ignoring USER" (conform with unfollowing)

The next couple of commands have some unexpected, superfluous words. Very frustrating when you get a command wrong. We should smooth these out. We probably need to keep the superfluous words for when we run in to conflicts, so my advice would be to support both:

- "Sempai assign role 'role' to user USER" -> "Sempai assign ROLE to USER". 
- "Sempai enable module MODULE NAME" ->"Sempai enable MODULE NAME" (Same here)
- "Sempai disable module MODULE NAME" ->"Sempai disable MODULE NAME"
- "Sempai add permission PERMISSION NAME to role ROLE NAME" -> "Sempai add PERMISSION to ROLE"
- "Sempai add permission PERMISSION NAME from role ROLE NAME" -> "Sempai remove PERMISSION from ROLE"

There's also an argument to be made for both of the following to exist:

- "Sempai go to CHANNEL" and "Sempai go to channel CHANNEL" 

The next ones, I feel like we can bundle under specific keywords better, like the "show" or "list" keywords, to be more consistent.

- "Sempai who are you following" -> "Sempai list following/follows" and/or
- "Sempai show follow list" (following list, follows list)
- "Sempai what are my permissions" -> "Sempai show my permissions" and/or "Sempai show my permission(s) list" and/or "Sempai list my permissions"
- "Sempai help me" -> "Sempai show help" (might as well...)
- "Sempai show ignorelist" -> "Sempai show ignore list" and/or "Sempai list ignores"

**Comment by calvinbaart** [comment]
Alright, seems to be solved now with 25e9278
