### ISSUE TITLE
[osu!module] Reduce number of API calls

### ISSUE THREAD

**Issue by Chezus** [thememesquad/sempaibot#23]
We need a system to reduce the number of API calls so it doesn't add 64 calls an hour per new user. At the very least, we probably want a system to battle "dead" users, by figuring out a way to update them a lesser amount of times.

We need to have a discussion about this.

**Comment by calvinbaart** [comment]
Added basic decay system in 51e5ac19afe1c0ba666a6549be81196756c28b81
