### ISSUE TITLE
Permission system

### ISSUE THREAD

**Issue by calvinbaart** [thememesquad/sempaibot#7]
- [x] Superadmin, Admin, Moderator and Normal roles.
- [x] Give the Superadmin role all the permissions.
- [x] Assign Admin role to the owner of the server.
  - [x] Allow Admin role to assign the Admin, Moderator and Normal role to other people.
- [x] Moderator role:
  - [x] Allow the Moderator role to make sempai ignore certain users.
- [x] Assign Normal role by default

Example permissions:
- [x] OSU_FOLLOW
- [x] OSU_UNFOLLOW
- [x] MANAGE_MODULES
- [x] BLACKLIST_SERVERS
- [x] BLACKLIST_USERS
- [x] IGNORE_USERS
- [x] MANAGE_PERMISSIONS
- [x] ASSIGN_ROLES

### Permissions
- [x] sempai give ... role ....
- [x] sempai what are my permissions
- [x] sempai what is my role
- [x] sempai add permission .... to role ....
- [x] sempai remove permission .... from role ....

### Blacklist & Ignore
- [x] sempai ignore user ....
- [x] sempai unignore user ...
- [x] sempai show ignorelist

### Module
- [x] sempai enable module ....
- [x] sempai disable module ....
- [x] sempai list modules

**Comment by Chezus** [comment]
I think it's fine like this. Good job.

**Comment by calvinbaart** [comment]
This issue first requires #8 to be implemented though.

**Comment by calvinbaart** [comment]
Split off the blacklist stuff into a separate issue: #11
